# Generated by Django 4.2.7 on 2023-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caravailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'caravailability',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=30)),
                ('engine_capacity', models.FloatField(default=0.0)),
                ('door_number', models.IntegerField(default=0)),
                ('fuel_consumption_per_100km', models.CharField(max_length=50)),
                ('number_of_airbags', models.IntegerField()),
                ('description', models.CharField(default=None, max_length=100000)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/fotki')),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
