# Generated by Django 4.2.7 on 2023-11-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caravailability',
            name='car_select',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.cars'),
        ),
    ]
